baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Cantine'
theme = "blank"


[caches]
  [caches.images]
    dir = ':cacheDir/images'


[[menu.main]]
  name = "La cantine"
  url = "/"
   weight = 1

[[menu.main]]
  name = "Coworking"
  url = "/page/Coworking/"
   weight = 2

[[menu.main]]
  name = "Événement"
  url = "/page/Evenement"
   weight = 3

[[menu.main]]
  name = "Podcast"
  url = "/page/Podcast"
   weight = 4